const dataShop = {
    shopItems: [
      {
        id: 7,
        img: "./images/shop/shops-1.png",
        name: "Polo-Cotton KAS",
        price: "180",
        discount: "25",
      },
      {
        id: 8,
        img: "./images/shop/shops-2.jpg",
        name: "Polo-Cotton ADA",
        price: "120",
        discount: "10",
      },
      {
        id: 9,
        img: "./images/shop/shops-3.jpg",
        name: "Polo-Cotton AWK",
        price: "20",
        discount: "50 ",
      },
      {
        id: 10,
        img: "./images/shop/shops-4.jpg",
        name: "Polo-Cotton AWQ",
        price: "999",
        discount: "10 ",
      },
      {
        id: 11,
        img: "./images/shop/shops-5.jpg",
        name: "Polo-Cotton SDK",
        price: "80",
        discount: "20 ",
      },
      {
        id: 12,
        img: "./images/shop/shops-6.jpg",
        name: "Polo-Cotton UAK",
        price: "400",
        discount: "20 ",
      },
      {
        id: 13,
        img: "./images/shop/shops-7.jpg",
        name: "Polo-Cotton KAS",
        price: "60",
        discount: "5 ",
      },
      {
        id: 14,
        img: "./images/shop/shops-8.jpg",
        name: "Caps Baseball PSO",
        price: "120",
        discount: "10",
      },
      {
        id: 15,
        img: "./images/shop/shops-9.jpg",
        name: "Caps Panama USL",
        price: "53",
        discount: "7",
    },
    {
      id: 16,
      img: "./images/shop/shops-10.jpg",
      name: "Caps Panama LAU",
      price: "19",
      discount: "5",
    },
    {
      id: 17,
      img: "./images/shop/shops-11.jpg",
      name: "Polo-Cotton YAH",
      price: "52",
      discount: "4",
    },
    {
      id: 18,
      img: "./images/shop/shops-12.png",
      name: "Caps Baseball ARG",
      price: "50",
      discount: "2",
    },
    ],
  }
export default dataShop;